spring:
  application:
    name: "demo.webflux.product"
  output:
    ansi:
      enabled: always
  sql:
    init:
      data-locations: "classpath:sql/schema.sql"
      mode: always
  r2dbc:
    url: r2dbc:h2:file:///./product;DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
logging:
  level:
    com.jpdr.apps.demo.webflux: DEBUG
    org.springframework.r2dbc: DEBUG
app:
  base-url:
    retailer: ${APP_BASE_URL_RETAILER}
